--BD EMPLEADOS
CREATE DATABASE EMPLEADOS1
GO
USE EMPLEADOS1
--EMPRESA(NUMEMP, PUESTO, SUELDO,TURNO,CARRERA_)
CREATE TABLE EMPRESA(
NUMEMP INT IDENTITY NOT NULL,
PUESTO INT,
SUELDO MONEY,
TURNO VARCHAR(12),
CARRERA VARCHAR(15))


--SE ALMACENA LA INFORMACION DE PUESTO GUARDANDOSE UNA CLAVE DE PUESTO Y DESCRPCION
CREATE TABLE PUESTO( 
CVEPUESTO INT IDENTITY NOT NULL,
DESCRIPCION VARCHAR(30))

--LLAVE PRIMARIA DE FORANEA NECESARIA
ALTER TABLE DBO.EMPRESA
ADD
PRIMARY KEY (NUMEMP) 

ALTER TABLE DBO.PUESTO
ADD
PRIMARY KEY (CVEPUESTO) 

ALTER TABLE DBO.EMPRESA
ADD
CONSTRAINT FK_E_P
FOREIGN KEY (PUESTO)
REFERENCES PUESTO(CVEPUESTO)

--INSERTA 3 REGISTROS EN CADA TABLA
INSERT INTO PUESTO VALUES('Gerente')
INSERT INTO PUESTO VALUES('Empleado Piso')
INSERT INTO PUESTO VALUES('Cajero')

INSERT INTO EMPRESA VALUES(1,5822,'M','ISC')
INSERT INTO EMPRESA VALUES(1,238,'M','ISC')
INSERT INTO EMPRESA VALUES (1,522,'M','ISC')


--MODIFICA LOS DATOS DEL EMPLEADO 2, INSERTANDO SU INFORMACION
UPDATE EMPRESA SET PUESTO=2 WHERE NUMEMP=1
UPDATE EMPRESA SET PUESTO=2 WHERE NUMEMP=2
UPDATE EMPRESA SET PUESTO=2 WHERE NUMEMP=3

--TABLA EMPLEADO
CREATE TABLE EMPLEADO( 
ID_EMPLEADO INT IDENTITY NOT NULL,
NOMBRE VARCHAR(30),
HORAST INT )

SELECT * FROM EMPLEADO

--MODIFICA LA TABLA EMPLEADO AGREGA UN ATRIBUO DENOMINADO RFC
ALTER TABLE EMPRESA
ADD RFC VARCHAR(20)

SELECT * FROM EMPRESA

--INSERTA VALORES EN EL RFC DE LA TABLA EMPLEADOS
UPDATE EMPRESA SET RFC='RDDDFFF' WHERE NUMEMP=1
UPDATE EMPRESA SET RFC='RDDDFFF' WHERE NUMEMP=2
UPDATE EMPRESA SET RFC='RDDDFFF' WHERE NUMEMP=3

--CREA UNA REGLA QUE GARANTICE QUE LA INFORMACION DE LAS HORAS TRABAJADAS NO EXCEDA DE LAS 40 HRS
CREATE RULE HORA
AS @HORAS<=40

--EJECUTA LA REGLA CON UN ATRIBUTO HORAS T, EN LA TANLA EMPLEADO
EXEC sp_bindrule HORA,'EMPLEADO.HORAST'

--CREA UN VALOR POR DEFAULT DENOMINADO DF_CARRERA DFCARERA CON EL VALOR ING SISTEMAS
CREATE DEFAULT DF_CARRERA AS 'ING.SISTEMAS'

-- VINCULA EL VALOR POR DEFAULT  DENOMINADO DFCARRERA AL ATRIBUTO DE LA TABLA EMPLEADO
EXEC sp_bindefault DF_CARRERA ,'EMPRESA.CARRERA'

-- AGREGA UNA CAPSULA CHECK QUE GARANTICE QUE EL NUMERO EMPLEADOS ESTARA ENTRE LOS VALORES 1-999
ALTER TABLE DBO.EMPRESA
ADD
CONSTRAINT NEMPLEADOS
CHECK(NUMEMP BETWEEN 1 AND 999 )

--CREA UNA RESTRICRICION QUE GARANTICE QUE EL TURNO SOLO SERA MATUTINO O DESPERTINO
ALTER TABLE DBO.EMPRESA
ADD
CONSTRAINT TURNOSS
 check (TURNO='M' OR TURNO='D')
 
