--CREAR BD
CREATE DATABASE CONGRESO
GO
--USAR BD
USE CONGRESO

--•	CREA UN TIPO DE DATO DENOMINADO TEXTO QUE SEA DE TIPO CHAR (15).
EXEC SP_ADDTYPE TEXTO, 'CHAR(15)'

--CREAR TABLA
CREATE TABLE PARTICIPANTES(
NOREGISTRO INT IDENTITY,
APPATERNO TEXTO,
APMATERNO TEXTO,
NOMBRE TEXTO,
DIRECCION VARCHAR(30),
TELEFONO VARCHAR(20),
UNIVORIGEN INT NOT NULL,
AREAINSCRIPCION VARCHAR(15),
MONTOINSCRIPCION MONEY
)

/*	CREE UNA REGLA QUE GARANTICE QUE EL ÁREA_INSCRIPCION
 SOLO SERÁ UNO DE LOS VALORES (TECNOLOGIAS DE LA INFORMACION,
  SISTEMAS, ADMINISTRACION, PRODUCCION)*/
create rule RG_INSCRIPCION
as @AREAINSCRIPCIONN IN ('TECNOLOGIAS DE LA INFORMACION','SISTEMAS', 'ADMINISTRACION', 'PRODUCCION');  
GO
--ENLAZA LA REGLA AL ATRIBUTO AREAINSCRIPCION.
exec sp_bindrule  RG_INSCRIPCION, 'PARTICIPANTES.AREAINSCRIPCION'


--CREA LA TABLA UNIVERSIDADES, DEFINE SU LLAVE PRIMARIA.

CREATE TABLE UNIVERSIDADES(
IDUNI INT IDENTITY NOT NULL PRIMARY KEY,
UNIVERSIDAD VARCHAR(20))



/*DEFINE COMO LLAVE FORÁNEA, A LA TABLA PARTICIPANTES
 EL ATRIBUTO UNIVORIGEN, QUE HAGA REFERENCIA 
 A UNA TABLA DENOMINADA UNIVERSIDADES*/
ALTER TABLE DBO.PARTICIPANTES
ADD CONSTRAINT FK_PARTICIPANTES_UNIVERSIDADES
FOREIGN KEY (UNIVORIGEN)
REFERENCES DBO.UNIVERSIDADES(IDUNI)

--AGREGA A LA TABLA A PARTICIPANTES UN ATRIBUTO DENOMINADO LUGARCONGRESO
ALTER TABLE DBO.PARTICIPANTES
ADD LUGARCONGRESO VARCHAR(30)

/*CREA UNA REGLA DENOMINADA FORMATOTEL, QUE GARANTICE QUE EL TELÉFONO
 TENGA COMO FORMATO LA ESTRUCTURA 664-999-99-99 (ESTO ES LOS TRES PRIMEROS
  DÍGITOS SEAN 664, SEGUIDO DE 3 CARACTERES, DOS CARACTERES, DOS CARACTERES)*/4
  CREATE RULE FORMATOTELE 
  AS  
@value LIKE '664-___-__-__%[0-9]'  
GO
exec sp_bindrule  FORMATOTELE, 'PARTICIPANTES.TELEFONO'

/*AGREGA EL ATRIBUTO ACTSOCIAL DE TIPO INT, AGREGA UNA RESTRICCIÓN CHECK, QUE   
 GARANTICE QUE LOS VALORES CONTENIDOS SEAN SI O NO.*/
 ALTER TABLE DBO.PARTICIPANTES
 ADD ACTSOCIAL VARCHAR(2) 
 GO
 ALTER TABLE DBO.PARTICIPANTES
 ADD
 Constraint ck_ACTIVIDAD
 check (ACTSOCIAL='SI' OR ACTSOCIAL='NO')
 

--CREA UNA REGLA QUE GARANTICE QUE EL MONTOINSCRIPCION, SOLO SEA DE 4500.00 O  5500.00
Create Rule MONTO
As
@CANTINSCR = $4500 OR @CANTINSCR = $5500

exec sp_bindrule MONTO,'PARTICIPANTES.MONTOINSCRIPCION'


--CREA UN VALOR POR DEFAULT DENOMINADO CIUDAD, CON EL VALOR GUADALAJARA.
create default CUIDAD as 'GUADALAJARA'
--ASIGNA EL VALOR POR DEFAULT AL DATO CREADO DENOMINADO LUGAR CONGRESO.
exec sp_bindefault CUIDAD, 'PARTICIPANTES.LUGARCONGRESO'

--MOSTRAR TABLAS
SELECT * FROM PARTICIPANTES
SELECT * FROM UNIVERSIDADES

--INSERCIONES UNIVERSIDADES
INSERT  UNIVERSIDADES VALUES('TECTIJUANA')
INSERT  UNIVERSIDADES VALUES('TEC MONTERREY')
INSERT  UNIVERSIDADES VALUES('UABC')
INSERT  UNIVERSIDADES VALUES('UTT')

--INSERCIONES PARTICIPANTES
INSERT  PARTICIPANTES VALUES('MORALES','GALINDO','KAREN','CAÑADA','664-114-08-58',1,'SISTEMAS',5501.00,DEFAULT,'SI')

INSERT  PARTICIPANTES VALUES('MORALES','GALINDO','KAREN','CAÑADA','664-114-08-58',1,'SISTEMAS',5500.00,DEFAULT,'SI')