CREATE DATABASE PRACTICA9

USE PRACTICA9

EXEC sp_addtype valorreal, 'decimal(6,2)'


CREATE TABLE PRODUCTOS (
CVEPTO INT NOT NULL,
DESCRIPCION VARCHAR(30),
PRECIO valorreal,
TIPO VARCHAR(20))


ALTER TABLE DBO.PRODUCTOS
ADD CVELINEA INT NOT NULL


CREATE TABLE LINEA(
CVELINEA INT  PRIMARY KEY NOT NULL,
LINEA VARCHAR(20),
DESCRIPCION VARCHAR (30))


ALTER TABLE DBO.PRODUCTOS
ADD CONSTRAINT FK_LINEA_DEPARTAMENTO
FOREIGN KEY (CVELINEA)
REFERENCES DBO.LINEA(CVELINEA)

ALTER TABLE  DBO.PRODUCTOS
add
Constraint CK_CVELINEA
check (CVELINEA<=20)



ALTER TABLE  DBO.PRODUCTOS
add
Constraint CK_PRECIO
check (PRECIO>=1 AND  PRECIO <=9999.999)

create default TIPO as 'OFICINA'
exec sp_bindefault TIPO, 'PRODUCTOS.TIPO'


ALTER TABLE  DBO.LINEA 
ADD
check (DESCRIPCION LIKE'%lin%')

ALTER TABLE  DBO.LINEA 
drop
Constraint LK_DEv

drop table PRODUCTOS
DROP TABLE LINEA

INSERT INTO LINEA VALUES (1,'UNO','lin')
INSERT INTO LINEA VALUES (7,'UNO','kklin')


INSERT INTO PRODUCTOS VALUES(1,'COCA',2,DEFAULT,1)
INSERT INTO PRODUCTOS VALUES(3,'COS',2,DEFAULT,2)

SELECT * FROM PRODUCTOS
SELECT * FROM LINEA





