--CREAR BASE DE DATOS
CREATE DATABASE PRACTICA8

--USAR PRACTICAS
USE PRACTICA8

--CREAR TABLA
CREATE TABLE CLIENTE(
ID_CLIENTE INT NOT NULL,
NOMCLIENTE VARCHAR(30))

--AGREGAR LLAVE PRIMARIA
ALTER TABLE DBO.CLIENTE
ADD
CONSTRAINT ID_CLIENTE
PRIMARY KEY (ID_CLIENTE)

--AGREGAR RFC
ALTER TABLE DBO.CLIENTE
ADD RFC VARCHAR(30)
CONSTRAINT RFC UNIQUE (RFC)

--SELECCIONAR TODO
SELECT * FROM CLIENTE


--TABLA DEPARTAMENTO
CREATE TABLE DEPARTAMENTO(
IDDTOP INT PRIMARY KEY ,
NOMBRE VARCHAR(25))


--AGREGAR DEPARTAMENTO
ALTER TABLE DBO.CLIENTE
ADD IDDTOP INT

--AGREGAR LLAVE FORANEA
ALTER TABLE DBO.CLIENTE
ADD CONSTRAINT FK_DEPARTAMENTO_CLIENTE
FOREIGN KEY (IDDTOP)
REFERENCES DBO.DEPARTAMENTO(IDDTOP)

--INSERCIONES
INSERT INTO DEPARTAMENTO VALUES(1,'ELECTRONICA')
INSERT INTO DEPARTAMENTO VALUES(2,'PERFUMERIA')

--INSERCIONES CLIENTE
INSERT INTO CLIENTE VALUES (1,'JUAN','DFSDSDDD',1)
INSERT INTO CLIENTE VALUES (2,'JUAN','DD',2)
INSERT INTO CLIENTE VALUES (3, 'Juan Lopez', 'JLME950213JLM', 1)
INSERT INTO CLIENTE VALUES (4, 'Jorge Perez', 'JPEM690316JPE', 2)
INSERT INTO CLIENTE VALUES (6, 'Carmen Yee', 'Laar0303315', 2)
--NO HAY DEPARTAMENTO 3
INSERT INTO CLIENTE VALUES (5, 'Laura Arias', 'LAAR030315', 3)



--MIRAR TABLAS
SELECT * FROM  DEPARTAMENTO
SELECT * FROM  CLIENTE
 
 --AGREGAR CREDITO
ALTER TABLE DBO.CLIENTE
ADD CREDITO MONEY

 
 
--AGREGAR 
ALTER TABLE  DBO.CLIENTE
add
Constraint ck_CREDITO
check (CREDITO>1 AND CREDITO<10000)

--INSERCIONES CLIENTES CON CREDITO
INSERT INTO CLIENTE VALUES (7, 'Laura Arias', 'LAAR030315', 2,2)
INSERT INTO CLIENTE VALUES (8, 'Laura Arias', 'LAAR03031', 2,1000)
--NO ACEPTA CREDITO
INSERT INTO CLIENTE VALUES (8, 'Laura Arias', 'LAAR03315', 2,10000)


