CREATE DATABASE PC10
USE PC10

CREATE TABLE NUMEROS(
NUM1 INT,
NUM2 INT,
NUM3 INT 
)
INSERT INTO NUMEROS VALUES(0,1,3),(5,4,6)
INSERT INTO NUMEROS VALUES(0,5,2),(9,5,3)
//
create function DBO.NUME(@A INT,@B INT, @C INT)
returns int
as 
BEGIN
declare @NUMM int
IF(@A > @B AND @A > @C)
BEGIN
SET @NUMM=@A 
END

ELSE IF (@B > @A AND @B > @C)
BEGIN
SET @NUMM=@B
END

ELSE
BEGIN
SET @NUMM= @C
END

RETURN  @NUMM;
END

SELECT DBO.NUME(NUM1,NUM2,NUM3) AS 'NUMERO MAYOR' FROM NUMEROS
