CREATE DATABASE PRC08

USE PRC08

CREATE TABLE ALUMNO(
NUM_CONTROL INT IDENTITY PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(30),
APELLIDOP VARCHAR(30),
APELLIDOM VARCHAR(30),
CAL1 INT,
CAL2 INT,
CAL3 INT,
CAL4 INT
)

--FUNCION PROMEDIO
CREATE FUNCTION DBO.PROMEDIO(@CALI1 INT ,@CALI2 INT, @CALI3 INT , @CALI4 INT )
RETURNS decimal(4,2)
AS
BEGIN
DECLARE @PROMEDIO decimal(6,2)
SET @PROMEDIO= (@CALI1+@CALI2+@CALI3+@CALI4)/4;
RETURN @PROMEDIO
END

INSERT INTO ALUMNO VALUES('KAREN','MORALES','GALINDO', 100,70,80,100);
INSERT INTO ALUMNO VALUES('YAHARA','HERNANDEZ','CORDOVA', 100,90,80,100);
INSERT INTO ALUMNO VALUES('YURI','CHAVEZ','DUARTE', 100,90,90,100);
INSERT INTO ALUMNO VALUES('MANUEL','JAVIER','MORALES', 100,99,100,100);
SELECT * FROM ALUMNO

SELECT ALUMNO.NOMBRE,ALUMNO.APELLIDOP,ALUMNO.APELLIDOP,ALUMNO.CAL1,ALUMNO.CAL2,ALUMNO.CAL3,ALUMNO.CAL4,
DBO.PROMEDIO(ALUMNO.CAL1,ALUMNO.CAL2,ALUMNO.CAL3,ALUMNO.CAL4) AS 'PROMEDIO'  FROM ALUMNO
