--USAR BASE DE DATOS PUBS
USE PUBS

/* 1.-  COPIA EL RESULTADO OBTENIDO EN ESTA SENTENCIA*/

--COMBINA LA TABLA TITLES Y SALES Y MUESTRA COMO RESULTADO LAS COLUMNAS TITLES Y SALES
SELECT TITLE, PRICE FROM SALES LEFT OUTER JOIN TITLES ON SALES.TITLE_ID
= TITLES.TITLE_ID
WHERE (PRICE >= 7.00 AND PRICE <= 12.00)

GO
--LA OPCION NUMERO, VISTAS Y JOIN
CREATE VIEW DBO.TITLESVIEW
AS SELECT TITLE, PRICE FROM TITLES T LEFT OUTER JOIN SALES S
ON T.TITLE_ID = S.TITLE_ID
WHERE (T.PRICE >= 7.00 AND T.PRICE <= 12.00)
SELECT * FROM TITLESVIEW


--/* 2.- */EJECUTA Y EXPLICA ESTA SENTENCIA

--MUESTRA LOS CAMPOS TITLE_ID,TITLE,TYPE Y YTD_SALES CON LOS REGISTROS DE LAS TABLAS CONBINADAS TITLES Y SALES CUANDO LA FECHA ES IGUAL  '1994-09-13'
SELECT TITLES.TITLE_ID, TITLE, TYPE, YTD_SALES FROM TITLES LEFT OUTER JOIN SALES ON TITLES.TITLE_ID = SALES.TITLE_ID WHERE (ORD_DATE ='1994-09-13') 

/* 3.-  COPIA EL RESULTADO OBTENIDO EN ESTA SENTENCIA*/
--MUESTRA LOS TITULOS DE LOS LIBROS CUANDO EL PRECIO SEA >= 5 Y <= 15
SELECT * FROM SALES JOIN TITLES ON SALES.TITLE_ID = TITLES.TITLE_ID WHERE  PRICE >=5 AND  PRICE <=15

/* 4.- DESPLIEGA EL DETALLE DE VENTAS  EN EL QUE SE DESPLIEGEN LOS DATOS LOS TITULOS CUYO TIPO  DE GENERO  SEA NEGOCIOS  O PSICOLOGIA*/

--SE MUESTRA LOS LIBROS DEL TIPO PSYCHOLOGY O BUSINESS CON INNER JOIN
SELECT * FROM SALES INNER JOIN TITLES ON SALES.TITLE_ID=TITLES.TITLE_ID WHERE TYPE LIKE '%BUSINESS' OR  TYPE LIKE '%PSYCHOLOGY  '


/* 5.- DESPLIEGA EL DETALLE DE VENTAS EN EL QUE SE DEPLIEGEN LOS DATOS DE LOS TITULOS CUYO  TIPO DE GENERO NO SEA  NEGOCIOS  O PSICOLOGIA*/
--SE MUESTRA LOS LIBROS MIESTRAS EL TIPO DE LIBRO NO SEA PSYCHOLOGY Ó BUSINESS 
SELECT *FROM SALES INNER JOIN TITLES ON SALES.TITLE_ID=TITLES.TITLE_ID WHERE TYPE  NOT LIKE '%BUSINESS' AND  TYPE  NOT LIKE  '%PSYCHOLOGY'


/* 6.-  CONSULTA DEL PIZARRÓN: SELECT*FROM SALES.TITLE WHERE SALES.TITLE_ID = TITLES.TITLE_ID AND  TITLES.TITLE LIKE 'THE%' 
AL CODIGO QUE VENIA SOLO SE ADAPTO A INNER JOIN*/
SELECT *FROM SALES INNER JOIN TITLES ON SALES.TITLE_ID = TITLES.TITLE_ID WHERE TITLES.TITLE LIKE 'THE%'

/* 7.- DESPLIEGA EL DETALLE DE VENTAS EN EL QUE SE LISTEN LOS DATOS DE LOS 
LIBROS EN CUYO TITULO  CONTENGA LA PALABRA  COMPUTER ,DONDE QUIERA QUE SE ENCUENTREN */
--SE ESPECIFICA CON LA INSTRUCCION WHERE TITLE LIKE '%COMPUTER%' QUE MIENTRAS CONTENGA ESA PALABRA EL CAMPO TITLE MOSTRARA EL LIBRO
SELECT *FROM SALES INNER JOIN TITLES ON SALES.TITLE_ID=TITLES.TITLE_ID WHERE TITLE LIKE '%COMPUTER%'


/* 8.- DESPLIEGA EL DETALLE DE VENTAS EN EL QUE SE LISTEN LOS DATOS DE LOS LIBROS CUYO TITULO COMIENCE A,B,O C  
SIN IMPORTAR QUE SIGA DESPUES O BIEN CUYA SEGUNDA LETRA SEA H  SIN INPORTAR QUE SIGA  
DESPUES O BIEN CUYA  SEGUNDA LETRA SEA H , SIN IMPORTAR QUE LETRA ES LA INTERIOR NO QUE LETRAS  SIGAN DESPUE*/

/*SE HACE UN RANGO DE LETRAS DE LIBROS CON LOS QUE EMPIECE CON A,B O C Y OTRO RANGO DE LA A HASTA LA Z Y SE PONE ENSEGUIDA LA H 
PARA ESPECIFICAR QUE MIENTRAS LA H SEA LA SEGUNDA LETRA TAMBIEN LO MOSTRARA*/
SELECT *FROM SALES INNER JOIN TITLES ON SALES.TITLE_ID=TITLES.TITLE_ID WHERE TITLE LIKE '[A-C]%' OR TITLE LIKE '[A-Z][H]%'


/*9.- CONSULTA LA LISTA DE LOS TITULOS QUE SE HAN VENDIDO  AL MENOS UNA VEZ (DISTINCT)*/
--CON DISTINC ANTES DEL FROM Y ESPECIFICANDO EL CAMPO DE LA TABLA SOLO MOSTRARA LOS LIBROS QUE SE HALLAN VENDIDO UNA SOLA VEZ
SELECT DISTINCT (TITLE) FROM TITLES INNER JOIN SALES ON SALES.TITLE_ID=TITLES.TITLE_ID


