/*MORALES GALINDO KAREN NOHEMI */
--CREAR BD 
CREATE DATABASE PRAC9
--USAR BD
USE PRAC9
--CREAR TABLA
CREATE TABLE EMPLEADO(
ID_EMPLEADO INT NOT NULL PRIMARY KEY IDENTITY,
NOMBRE VARCHAR(35),
APELLIDOM VARCHAR(35),
APELLIDOP VARCHAR(35),
CATEGORIA INT,
HORAST INT,)

--INSERCIONES
INSERT INTO EMPLEADO VALUES ('Karen Nohemi', 'Morales','Galindo',101,5)
INSERT INTO EMPLEADO VALUES ('Karen Nohemi', 'Morales','Galindo',102,5)
INSERT INTO EMPLEADO VALUES ('Karen Nohemi', 'Morales','Galindo',103,5)



--FUNCION

CREATE function dbo.sueldo(@CATEGORIA INT)
RETURNS INT
AS
BEGIN
DECLARE @SUELDO INT
SET @SUELDO=
CASE
WHEN @CATEGORIA=101 THEN 120
WHEN @CATEGORIA=102 THEN 180
WHEN @CATEGORIA=103 THEN 220
ELSE 0
END 
RETURN @SUELDO
END

---SELECCIONAR SUELDO BRUTO
select EMPLEADO.NOMBRE,EMPLEADO.APELLIDOM,EMPLEADO.APELLIDOP,EMPLEADO.CATEGORIA, EMPLEADO.HORAST,
dbo.sueldo(EMPLEADO.CATEGORIA)AS'SUELDO', dbo.sueldo(EMPLEADO.CATEGORIA)*EMPLEADO.HORAST AS 'SUELDO BRUTO' 
FROM EMPLEADO