CREATE DATABASE PRACTICA2
GO

USE PRACTICA2
GO

CREATE TABLE ESTUDIANTE(
NOCONTROL VARCHAR(10) PRIMARY KEY,
APEPAT VARCHAR(20) NOT NULL,
APEMAT VARCHAR(20) NOT NULL,
NOMBRE VARCHAR(20) NOT NULL,
FECHANAC DATE,
CARRERAID INT NOT NULL
)

CREATE TABLE CARRERA(
CARRERAID INT PRIMARY KEY,
NOMBRE VARCHAR (40) UNIQUE NOT NULL
)

INSERT INTO ESTUDIANTE(NOCONTROL,APEPAT,APEMAT,NOMBRE,FECHANAC, CARRERAID)
VALUES ('97212658','TORRES','GARCIA','FERNANDO','05/10/1989',1)

INSERT INTO ESTUDIANTE(NOCONTROL,APEPAT,APEMAT,NOMBRE,FECHANAC, CARRERAID)
VALUES ('97212659','JIMENEZ','FLORES','NANCY','05/12/1988',1)

SELECT * FROM ESTUDIANTE

SELECT NOCONTROL,APEPAT,APEMAT, NOMBRE, FECHANAC, CARRERAID FROM ESTUDIANTE

--LA INSTRUCCION UPDATE [NOMBRE TABLA] SET [NOMBRE CAMPO1] ='', [NOMBRE CAMPO2] ='', ...
--LA INSTRUCCION WHERE PERMITE CONDICIONAR CRITERIOS
--EJEMPLO DE INSTRUCCION PERMITE ACTUALIZAR EL NOMBRE DE LA ESTUDIANTE CON EL NUMERO
--DE CONTROL 97212658 SU NOMBRE ORIGINAL NANCY A NANCY ESTHER
UPDATE ESTUDIANTE SET NOMBRE='NANCY ESTHER' WHERE NOCONTROL='97212659'

--LA INSTRUCCION DELETE FROM [NOMBRE TABLA] 
--LA INSTRUCCION WHERE PERMITE CONDICIONAR CRITERIOS
--EJEMPLO DE INSTRUCCION PERMITE BORRAR REGISTROS DE LA TABLA ESTUDIANTE DONDE EL
--NUMERO DE CONTROL ES 97212658
DELETE FROM ESTUDIANTE WHERE NOCONTROL='97212658'

-- LA INSTRUCCION INSERT INTO [NOMBRE TABLA] VALUES ([CAMPO1], [CAMPO2], ...)
-- EJEMPLO LAS SIGUIENTES INSTRUCCIONES PERMITEN INGRESAR DATOS A LA TABLA CARRERA

INSERT INTO CARRERA ( CARRERAID, NOMBRE)
VALUES (1, 'INGENIERIA EN SISTEMAS COMPUTACIONALES')

INSERT INTO CARRERA ( CARRERAID, NOMBRE)
VALUES (2, 'INGENIERIA INFORMATICA')

INSERT INTO CARRERA ( CARRERAID, NOMBRE)
VALUES (3, 'INGENIERIA TIC')

SELECT * FROM CARRERA